services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: students-api-app
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      PORT: 3000
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_NAME: students_db
    ports:
      - '3000:3000'
    restart: unless-stopped

  postgres:
    image: postgres:16-alpine
    container_name: students-api-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: students_db
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres -d students_db']
      interval: 5s
      timeout: 5s
      retries: 10
    ports:
      - '5432:5432'
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
